### ISSUE TITLE
Understand and handle rounding errors

### ISSUE THREAD

**Issue by tidoust** [w3c/i-slide#31]
From time to time, a tests can fail due to slightly incorrect reported dimensions, as in https://github.com/w3c/i-slide/runs/3718933940?check_suite_focus=true

```
1) Test loading slides
       loads a single b6+ slide:

      AssertionError [ERR_ASSERTION]: 299 == 300
      + expected - actual

      -299
      +300
      
      at Context.<anonymous> (test/i-slide.js:578:18)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

As far as I can tell, the final dimensions are correct, meaning that waiting a few ms is enough to get the right values. But the values should be correct to start with too, so it would be good to understand what causes these slight fluctuations and to handle them appropriately. It may be that these are due to rounding errors when applying some aspect ratio.

**Comment by tidoust** [comment]
The problem still pops up in tests once in a while. I don't manage to reproduce it locally.

Using `300px` as default width is consistent with images and iframes, but the `16/9` ratio means that the final height needs to be `168.75px`, which isn't an exact number of pixels, and browsers seem to apply some rounding to that somehow.

Loading a b6+ slide locally, I do get `300px` for the width, but then I get `168.81px` for the height of the HTML contents within the shadow DOM, which is very slightly incorrect, and `169px` for the `<i-slide>` container.

Anyway, not sure there's much we can do apart from making the test more lax about the dimensions it gets from Puppeteer.
